#ifndef BIT_MATH_H
#define BIT_MATH_H

#define SET_BIT(REG,BIT_POSITION)     	REG |= (1<<BIT_POSITION)
#define CLR_BIT(REG,BIT_POSITION)   	REG &= ~(1<<BIT_POSITION)
#define GET_BIT(REG,BIT_POSITION)     	(REG & (1<<BIT_POSITION))>>BIT_POSITION
#define TOG_BIT(REG,BIT_POSITION)  		REG ^= (1<<BIT_POSITION)

#endif
